# Site Settings
title: Fri Rasyidiâ€”UX+Visual Designer
email: fri@frirasyidi.com
description: >
  Fri is a UX+Visual Designer who builds useful products with common sense and user centeric approach.
baseurl: ""
url: "http://localhost:4000"
twitter_username: frirasyidi
github_username:  frirasyidi

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
